### ISSUE TITLE
Default Launcher Home Screen Still shows after closing apps

### ISSUE THREAD

**Issue by eternalapprentice2000** [BaronKiko/LauncherHijack#18] opened 2018-07-18 02:28 UTC
Fire HD 8 (7th generation) Fire OS 5.6.2.0

Installation went expected.  However, when pressing the square button (app button?) and then pressing the  triangle button (back button) you will be directed to the Default Home Screen.

Pressing the home button will take you back to the launcher screen.  In this case Nova Launcher.

I would personally like it to go back to the nova home screen when done switching apps.

Any thoughts?

Thanks

Kenneth Garza

**Comment by BaronKiko** [comment] 2018-07-18 07:12
Hmm, my tablet is out of battery so I can't test but that is what I thought it did. will do some more tests and get back to you.

**Comment by BaronKiko** [comment] 2018-07-18 21:40
Ok let's clear up replication steps.
So you are on the home screen, you press the app switcher then hit back and you are left on the default home screen?
Also if you used launcherhijack before 5.6.2.0 did this issue occur before the update?

**Comment by johnpercy** [comment] 2018-07-18 21:59
It turns out the Home button setting in Accessibility had turned itself off. That's odd in itself and I don't know how that happened..

**Comment by BaronKiko** [comment] 2018-07-18 22:18
Ok so with the setting reenabled the issue is resolved? Does that solve the issue for @eternalapprentice2000 too?

**Comment by johnpercy** [comment] 2018-07-19 12:15
It solved my problem! Sorry for the wrong call.
(BTW Despite documentation, Google Now launcher loads quickly and reliably (so far), with widgets, and no intermediate flash.)

**Comment by eternalapprentice2000** [comment] 2018-07-19 12:49
Thanks for looking into this.  I am at work at the moment and my tablet is at home enjoying the air conditioning.  I will look into this when I get home.

**Comment by BaronKiko** [comment] 2018-07-24 00:16
I'm closing as it seems like it was never really an issue.

**Closed by BaronKiko** 2018-07-24 00:16 UTC

**Comment by eternalapprentice2000** [comment] 2018-07-24 12:34
sorry, i was out of town, I checked these settings and found that resolved my issue as well.  Thanks for your due diligence.  Great Product!
